str1="race"
str2="care"
str1=str1.lower()
str2=str2.lower()
if(len(str1)==len(str2)):
    sorted_str1=sorted(str1)
    sorted_str=sorted(str2)
    if(sorted_str1==sorted_str):
        print("anagram")
    else:
        print("not")
else:
    print("not")
